name: Publish Docker Image
on:
  push:
    paths-ignore:
      - "*.md"

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Checkout Codes
      uses: actions/checkout@v2

    - name: Build Image
      run: |
        Copy-Item "C:/Windows/Fonts/msyh*.ttc" .
        docker build -t forewing/texlive-windows-container:latest .

    # - name: Publish Image
    #   env:
    #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    #   run: |
    #     Write-Output (Get-Item env:DOCKER_PASSWORD).value | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
    #     docker push forewing/texlive-windows-container:latest